# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-23 05:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('mal_title', models.CharField(max_length=255)),
                ('anime_type', models.CharField(max_length=255)),
                ('episodes', models.IntegerField(blank=True, null=True)),
                ('mal_id', models.IntegerField(blank=True, null=True)),
                ('mal_url', models.CharField(max_length=255)),
                ('mal_img_url', models.CharField(max_length=255)),
                ('mal_score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('filename', models.CharField(max_length=255)),
                ('sub_group', models.CharField(max_length=255)),
                ('episode_number', models.CharField(max_length=255)),
                ('subtitles', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('thumb', models.CharField(max_length=255)),
                ('crc32_hash', models.CharField(max_length=8)),
                ('filesize', models.IntegerField()),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='home_app.Anime')),
            ],
        ),
    ]
